# Generated by Django 5.0.6 on 2024-06-18 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_alter_car_f_compra_alter_car_f_matriculacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceite_litros', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('aceite_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('aceite_pedir', models.BooleanField(default=False)),
                ('aceite_cambio', models.BooleanField(default=False)),
                ('neumaticos_numero', models.IntegerField(blank=True, null=True)),
                ('neumaticos_medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('bateria', models.TextField(blank=True, null=True)),
                ('otros_recambios', models.TextField(blank=True, null=True)),
                ('otras_tareas', models.TextField(blank=True, null=True)),
                ('filtro_aceite', models.BooleanField(default=False)),
                ('filtro_aire', models.BooleanField(default=False)),
                ('filtro_hab', models.BooleanField(default=False)),
                ('distribucion', models.BooleanField(default=False)),
                ('escobilla_del', models.BooleanField(default=False)),
                ('escobilla_tras', models.BooleanField(default=False)),
                ('pastillas_del', models.BooleanField(default=False)),
                ('pastillas_tras', models.BooleanField(default=False)),
                ('liquido_frenos', models.BooleanField(default=False)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.car')),
            ],
        ),
    ]
