# Generated by Django 5.0.6 on 2024-06-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='bandeja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reception',
            name='bollos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reception',
            name='cristales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reception',
            name='doble_llave',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='embrague',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reception',
            name='f_reception',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='faros_pilotos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reception',
            name='granizo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reception',
            name='info_transporte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='n_recepcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='notas_doble_llave',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='pantalla',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reception',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='quemaduras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reception',
            name='recepcionador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='son_motor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reception',
            name='tarjeta_sd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reception',
            name='testigos',
            field=models.BooleanField(default=False),
        ),
    ]
