# Generated by Django 5.0.6 on 2024-06-16 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_car_f_compra_alter_car_f_matriculacion_and_more'),
        ('reception', '0002_reception_bandeja_reception_bollos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='car',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.car'),
        ),
    ]
