# Generated by Django 5.0.6 on 2024-06-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('matricula', models.CharField(max_length=80, unique=True)),
                ('stock', models.BooleanField(default=True)),
                ('destino', models.CharField(blank=True, max_length=50, null=True)),
                ('expediente', models.CharField(blank=True, max_length=80, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('f_matriculacion', models.DateField()),
                ('f_compra', models.DateField(blank=True, null=True)),
                ('f_ultima_itv', models.DateField(blank=True, null=True)),
                ('f_prox_itv', models.DateField(blank=True, null=True)),
                ('km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cambio', models.CharField(blank=True, max_length=50, null=True)),
                ('combustible', models.CharField(blank=True, max_length=50, null=True)),
                ('chasis', models.CharField(max_length=30)),
                ('t_motor', models.CharField(blank=True, max_length=50, null=True)),
                ('c_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('carroceria', models.CharField(blank=True, max_length=50, null=True)),
                ('servi_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consumo_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maletero', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('c_contaminacion', models.CharField(blank=True, max_length=50, null=True)),
                ('documented', models.BooleanField(default=False)),
            ],
        ),
    ]
