# Generated by Django 5.0.6 on 2024-05-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=80, unique=True)),
                ('chassis', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration_date', models.DateField(null=True)),
                ('documented', models.BooleanField(default=False)),
            ],
        ),
    ]
