# Generated by Django 5.0.6 on 2024-05-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
