# Generated by Django 5.0.6 on 2024-06-06 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.client'),
        ),
        migrations.AddField(
            model_name='car',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brand'),
        ),
    ]
