# Generated by Django 5.0.6 on 2024-06-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_car_f_compra_alter_car_f_matriculacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='f_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='f_matriculacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='f_prox_itv',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='f_ultima_itv',
            field=models.DateField(blank=True, null=True),
        ),
    ]
