# Generated by Django 5.0.6 on 2024-06-06 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.province')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=15, null=True)),
                ('telef', models.CharField(blank=True, max_length=15, null=True)),
                ('telef_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('telef_2', models.CharField(blank=True, max_length=15, null=True)),
                ('telef_2_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('empresa', models.BooleanField(default=False)),
                ('e_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('e_dni', models.CharField(blank=True, max_length=15, null=True)),
                ('cap_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('cap_dni', models.CharField(blank=True, max_length=15, null=True)),
                ('cap_direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('cap_cp', models.IntegerField(blank=True, null=True)),
                ('compras_cuenta', models.CharField(blank=True, max_length=100, null=True)),
                ('matricula_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_cliente_calcu', models.CharField(blank=True, max_length=100, null=True)),
                ('cap_localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cap_localidad', to='sales.municipality')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.municipality')),
                ('cap_provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cap_provincia', to='sales.province')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.province')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_venta', models.DateField(blank=True, null=True)),
                ('t_iva', models.CharField(blank=True, max_length=50, null=True)),
                ('garantia', models.CharField(blank=True, max_length=50, null=True)),
                ('garantia_fab_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('garantia_fab_fecha', models.DateField(blank=True, null=True)),
                ('garantia_ext_num', models.CharField(blank=True, max_length=50, null=True)),
                ('doble_precio', models.BooleanField(default=False)),
                ('p_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('p_financiado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('p_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('p_venta_modif', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('p_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('info_ventas', models.TextField(blank=True, null=True)),
                ('info_admin', models.TextField(blank=True, null=True)),
                ('info_taller', models.TextField(blank=True, null=True)),
                ('info_publi', models.TextField(blank=True, null=True)),
                ('info_transporte', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('hora_entrega', models.TimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.car')),
                ('vendedor', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.saler')),
            ],
        ),
    ]
