# Generated by Django 5.0.6 on 2024-06-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sales_vendedor_delete_saler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='doble_precio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
